// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Adz-ai/proxmox-cli/internal/interfaces (interfaces: ProxmoxClientInterface,NodeInterface,ContainerInterface,VirtualMachineInterface,ClusterInterface,StorageInterface)
//
// Generated by this command:
//
//	mockgen -destination=../../test/mocks/proxmox_client.go -package=mocks github.com/Adz-ai/proxmox-cli/internal/interfaces ProxmoxClientInterface,NodeInterface,ContainerInterface,VirtualMachineInterface,ClusterInterface,StorageInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	interfaces "github.com/Adz-ai/proxmox-cli/internal/interfaces"
	proxmox "github.com/luthermonson/go-proxmox"
	gomock "go.uber.org/mock/gomock"
)

// MockProxmoxClientInterface is a mock of ProxmoxClientInterface interface.
type MockProxmoxClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProxmoxClientInterfaceMockRecorder
	isgomock struct{}
}

// MockProxmoxClientInterfaceMockRecorder is the mock recorder for MockProxmoxClientInterface.
type MockProxmoxClientInterfaceMockRecorder struct {
	mock *MockProxmoxClientInterface
}

// NewMockProxmoxClientInterface creates a new mock instance.
func NewMockProxmoxClientInterface(ctrl *gomock.Controller) *MockProxmoxClientInterface {
	mock := &MockProxmoxClientInterface{ctrl: ctrl}
	mock.recorder = &MockProxmoxClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProxmoxClientInterface) EXPECT() *MockProxmoxClientInterfaceMockRecorder {
	return m.recorder
}

// Cluster mocks base method.
func (m *MockProxmoxClientInterface) Cluster(ctx context.Context) (interfaces.ClusterInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cluster", ctx)
	ret0, _ := ret[0].(interfaces.ClusterInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cluster indicates an expected call of Cluster.
func (mr *MockProxmoxClientInterfaceMockRecorder) Cluster(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cluster", reflect.TypeOf((*MockProxmoxClientInterface)(nil).Cluster), ctx)
}

// Node mocks base method.
func (m *MockProxmoxClientInterface) Node(ctx context.Context, nodeName string) (interfaces.NodeInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Node", ctx, nodeName)
	ret0, _ := ret[0].(interfaces.NodeInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Node indicates an expected call of Node.
func (mr *MockProxmoxClientInterfaceMockRecorder) Node(ctx, nodeName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Node", reflect.TypeOf((*MockProxmoxClientInterface)(nil).Node), ctx, nodeName)
}

// Nodes mocks base method.
func (m *MockProxmoxClientInterface) Nodes(ctx context.Context) (proxmox.NodeStatuses, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Nodes", ctx)
	ret0, _ := ret[0].(proxmox.NodeStatuses)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Nodes indicates an expected call of Nodes.
func (mr *MockProxmoxClientInterfaceMockRecorder) Nodes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Nodes", reflect.TypeOf((*MockProxmoxClientInterface)(nil).Nodes), ctx)
}

// Version mocks base method.
func (m *MockProxmoxClientInterface) Version(ctx context.Context) (*proxmox.Version, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version", ctx)
	ret0, _ := ret[0].(*proxmox.Version)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Version indicates an expected call of Version.
func (mr *MockProxmoxClientInterfaceMockRecorder) Version(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*MockProxmoxClientInterface)(nil).Version), ctx)
}

// MockNodeInterface is a mock of NodeInterface interface.
type MockNodeInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNodeInterfaceMockRecorder
	isgomock struct{}
}

// MockNodeInterfaceMockRecorder is the mock recorder for MockNodeInterface.
type MockNodeInterfaceMockRecorder struct {
	mock *MockNodeInterface
}

// NewMockNodeInterface creates a new mock instance.
func NewMockNodeInterface(ctrl *gomock.Controller) *MockNodeInterface {
	mock := &MockNodeInterface{ctrl: ctrl}
	mock.recorder = &MockNodeInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNodeInterface) EXPECT() *MockNodeInterfaceMockRecorder {
	return m.recorder
}

// Container mocks base method.
func (m *MockNodeInterface) Container(ctx context.Context, vmid int) (interfaces.ContainerInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Container", ctx, vmid)
	ret0, _ := ret[0].(interfaces.ContainerInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Container indicates an expected call of Container.
func (mr *MockNodeInterfaceMockRecorder) Container(ctx, vmid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Container", reflect.TypeOf((*MockNodeInterface)(nil).Container), ctx, vmid)
}

// Containers mocks base method.
func (m *MockNodeInterface) Containers(ctx context.Context) (proxmox.Containers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Containers", ctx)
	ret0, _ := ret[0].(proxmox.Containers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Containers indicates an expected call of Containers.
func (mr *MockNodeInterfaceMockRecorder) Containers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Containers", reflect.TypeOf((*MockNodeInterface)(nil).Containers), ctx)
}

// NewContainer mocks base method.
func (m *MockNodeInterface) NewContainer(ctx context.Context, vmid int, options ...proxmox.ContainerOption) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, vmid}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewContainer", varargs...)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewContainer indicates an expected call of NewContainer.
func (mr *MockNodeInterfaceMockRecorder) NewContainer(ctx, vmid any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, vmid}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewContainer", reflect.TypeOf((*MockNodeInterface)(nil).NewContainer), varargs...)
}

// NewVirtualMachine mocks base method.
func (m *MockNodeInterface) NewVirtualMachine(ctx context.Context, vmid int, options ...proxmox.VirtualMachineOption) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, vmid}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewVirtualMachine", varargs...)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewVirtualMachine indicates an expected call of NewVirtualMachine.
func (mr *MockNodeInterfaceMockRecorder) NewVirtualMachine(ctx, vmid any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, vmid}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewVirtualMachine", reflect.TypeOf((*MockNodeInterface)(nil).NewVirtualMachine), varargs...)
}

// Storage mocks base method.
func (m *MockNodeInterface) Storage(ctx context.Context, name string) (interfaces.StorageInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Storage", ctx, name)
	ret0, _ := ret[0].(interfaces.StorageInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Storage indicates an expected call of Storage.
func (mr *MockNodeInterfaceMockRecorder) Storage(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Storage", reflect.TypeOf((*MockNodeInterface)(nil).Storage), ctx, name)
}

// Storages mocks base method.
func (m *MockNodeInterface) Storages(ctx context.Context) (proxmox.Storages, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Storages", ctx)
	ret0, _ := ret[0].(proxmox.Storages)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Storages indicates an expected call of Storages.
func (mr *MockNodeInterfaceMockRecorder) Storages(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Storages", reflect.TypeOf((*MockNodeInterface)(nil).Storages), ctx)
}

// Tasks mocks base method.
func (m *MockNodeInterface) Tasks(ctx context.Context, options *proxmox.NodeTasksOptions) ([]*proxmox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tasks", ctx, options)
	ret0, _ := ret[0].([]*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Tasks indicates an expected call of Tasks.
func (mr *MockNodeInterfaceMockRecorder) Tasks(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tasks", reflect.TypeOf((*MockNodeInterface)(nil).Tasks), ctx, options)
}

// VirtualMachine mocks base method.
func (m *MockNodeInterface) VirtualMachine(ctx context.Context, vmid int) (interfaces.VirtualMachineInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VirtualMachine", ctx, vmid)
	ret0, _ := ret[0].(interfaces.VirtualMachineInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VirtualMachine indicates an expected call of VirtualMachine.
func (mr *MockNodeInterfaceMockRecorder) VirtualMachine(ctx, vmid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VirtualMachine", reflect.TypeOf((*MockNodeInterface)(nil).VirtualMachine), ctx, vmid)
}

// VirtualMachines mocks base method.
func (m *MockNodeInterface) VirtualMachines(ctx context.Context) (proxmox.VirtualMachines, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VirtualMachines", ctx)
	ret0, _ := ret[0].(proxmox.VirtualMachines)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VirtualMachines indicates an expected call of VirtualMachines.
func (mr *MockNodeInterfaceMockRecorder) VirtualMachines(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VirtualMachines", reflect.TypeOf((*MockNodeInterface)(nil).VirtualMachines), ctx)
}

// Vzdump mocks base method.
func (m *MockNodeInterface) Vzdump(ctx context.Context, options *proxmox.VirtualMachineBackupOptions) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Vzdump", ctx, options)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Vzdump indicates an expected call of Vzdump.
func (mr *MockNodeInterfaceMockRecorder) Vzdump(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Vzdump", reflect.TypeOf((*MockNodeInterface)(nil).Vzdump), ctx, options)
}

// MockContainerInterface is a mock of ContainerInterface interface.
type MockContainerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockContainerInterfaceMockRecorder
	isgomock struct{}
}

// MockContainerInterfaceMockRecorder is the mock recorder for MockContainerInterface.
type MockContainerInterfaceMockRecorder struct {
	mock *MockContainerInterface
}

// NewMockContainerInterface creates a new mock instance.
func NewMockContainerInterface(ctrl *gomock.Controller) *MockContainerInterface {
	mock := &MockContainerInterface{ctrl: ctrl}
	mock.recorder = &MockContainerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContainerInterface) EXPECT() *MockContainerInterfaceMockRecorder {
	return m.recorder
}

// AddTag mocks base method.
func (m *MockContainerInterface) AddTag(ctx context.Context, value string) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTag", ctx, value)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTag indicates an expected call of AddTag.
func (mr *MockContainerInterfaceMockRecorder) AddTag(ctx, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTag", reflect.TypeOf((*MockContainerInterface)(nil).AddTag), ctx, value)
}

// Clone mocks base method.
func (m *MockContainerInterface) Clone(ctx context.Context, options *proxmox.ContainerCloneOptions) (int, *proxmox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clone", ctx, options)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(*proxmox.Task)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Clone indicates an expected call of Clone.
func (mr *MockContainerInterfaceMockRecorder) Clone(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clone", reflect.TypeOf((*MockContainerInterface)(nil).Clone), ctx, options)
}

// Config mocks base method.
func (m *MockContainerInterface) Config(ctx context.Context, options ...proxmox.ContainerOption) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Config", varargs...)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Config indicates an expected call of Config.
func (mr *MockContainerInterfaceMockRecorder) Config(ctx any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockContainerInterface)(nil).Config), varargs...)
}

// Delete mocks base method.
func (m *MockContainerInterface) Delete(ctx context.Context, options *proxmox.ContainerDeleteOptions) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, options)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockContainerInterfaceMockRecorder) Delete(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockContainerInterface)(nil).Delete), ctx, options)
}

// DeleteSnapshot mocks base method.
func (m *MockContainerInterface) DeleteSnapshot(ctx context.Context, name string) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSnapshot", ctx, name)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSnapshot indicates an expected call of DeleteSnapshot.
func (mr *MockContainerInterfaceMockRecorder) DeleteSnapshot(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSnapshot", reflect.TypeOf((*MockContainerInterface)(nil).DeleteSnapshot), ctx, name)
}

// Details mocks base method.
func (m *MockContainerInterface) Details() interfaces.ContainerDetails {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Details")
	ret0, _ := ret[0].(interfaces.ContainerDetails)
	return ret0
}

// Details indicates an expected call of Details.
func (mr *MockContainerInterfaceMockRecorder) Details() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Details", reflect.TypeOf((*MockContainerInterface)(nil).Details))
}

// Migrate mocks base method.
func (m *MockContainerInterface) Migrate(ctx context.Context, options *proxmox.ContainerMigrateOptions) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Migrate", ctx, options)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Migrate indicates an expected call of Migrate.
func (mr *MockContainerInterfaceMockRecorder) Migrate(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Migrate", reflect.TypeOf((*MockContainerInterface)(nil).Migrate), ctx, options)
}

// NewSnapshot mocks base method.
func (m *MockContainerInterface) NewSnapshot(ctx context.Context, name string) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSnapshot", ctx, name)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewSnapshot indicates an expected call of NewSnapshot.
func (mr *MockContainerInterfaceMockRecorder) NewSnapshot(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSnapshot", reflect.TypeOf((*MockContainerInterface)(nil).NewSnapshot), ctx, name)
}

// Reboot mocks base method.
func (m *MockContainerInterface) Reboot(ctx context.Context) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reboot", ctx)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reboot indicates an expected call of Reboot.
func (mr *MockContainerInterfaceMockRecorder) Reboot(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reboot", reflect.TypeOf((*MockContainerInterface)(nil).Reboot), ctx)
}

// RemoveTag mocks base method.
func (m *MockContainerInterface) RemoveTag(ctx context.Context, value string) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTag", ctx, value)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveTag indicates an expected call of RemoveTag.
func (mr *MockContainerInterfaceMockRecorder) RemoveTag(ctx, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTag", reflect.TypeOf((*MockContainerInterface)(nil).RemoveTag), ctx, value)
}

// Resize mocks base method.
func (m *MockContainerInterface) Resize(ctx context.Context, disk, size string) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resize", ctx, disk, size)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resize indicates an expected call of Resize.
func (mr *MockContainerInterfaceMockRecorder) Resize(ctx, disk, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resize", reflect.TypeOf((*MockContainerInterface)(nil).Resize), ctx, disk, size)
}

// Resume mocks base method.
func (m *MockContainerInterface) Resume(ctx context.Context) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resume", ctx)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resume indicates an expected call of Resume.
func (mr *MockContainerInterfaceMockRecorder) Resume(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resume", reflect.TypeOf((*MockContainerInterface)(nil).Resume), ctx)
}

// RollbackSnapshot mocks base method.
func (m *MockContainerInterface) RollbackSnapshot(ctx context.Context, name string, start bool) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackSnapshot", ctx, name, start)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RollbackSnapshot indicates an expected call of RollbackSnapshot.
func (mr *MockContainerInterfaceMockRecorder) RollbackSnapshot(ctx, name, start any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackSnapshot", reflect.TypeOf((*MockContainerInterface)(nil).RollbackSnapshot), ctx, name, start)
}

// Shutdown mocks base method.
func (m *MockContainerInterface) Shutdown(ctx context.Context, force bool, timeout int) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", ctx, force, timeout)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockContainerInterfaceMockRecorder) Shutdown(ctx, force, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockContainerInterface)(nil).Shutdown), ctx, force, timeout)
}

// Snapshots mocks base method.
func (m *MockContainerInterface) Snapshots(ctx context.Context) ([]*proxmox.ContainerSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshots", ctx)
	ret0, _ := ret[0].([]*proxmox.ContainerSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Snapshots indicates an expected call of Snapshots.
func (mr *MockContainerInterfaceMockRecorder) Snapshots(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshots", reflect.TypeOf((*MockContainerInterface)(nil).Snapshots), ctx)
}

// Start mocks base method.
func (m *MockContainerInterface) Start(ctx context.Context) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockContainerInterfaceMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockContainerInterface)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockContainerInterface) Stop(ctx context.Context) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stop indicates an expected call of Stop.
func (mr *MockContainerInterfaceMockRecorder) Stop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockContainerInterface)(nil).Stop), ctx)
}

// Suspend mocks base method.
func (m *MockContainerInterface) Suspend(ctx context.Context) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Suspend", ctx)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Suspend indicates an expected call of Suspend.
func (mr *MockContainerInterfaceMockRecorder) Suspend(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Suspend", reflect.TypeOf((*MockContainerInterface)(nil).Suspend), ctx)
}

// MockVirtualMachineInterface is a mock of VirtualMachineInterface interface.
type MockVirtualMachineInterface struct {
	ctrl     *gomock.Controller
	recorder *MockVirtualMachineInterfaceMockRecorder
	isgomock struct{}
}

// MockVirtualMachineInterfaceMockRecorder is the mock recorder for MockVirtualMachineInterface.
type MockVirtualMachineInterfaceMockRecorder struct {
	mock *MockVirtualMachineInterface
}

// NewMockVirtualMachineInterface creates a new mock instance.
func NewMockVirtualMachineInterface(ctrl *gomock.Controller) *MockVirtualMachineInterface {
	mock := &MockVirtualMachineInterface{ctrl: ctrl}
	mock.recorder = &MockVirtualMachineInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVirtualMachineInterface) EXPECT() *MockVirtualMachineInterfaceMockRecorder {
	return m.recorder
}

// AddTag mocks base method.
func (m *MockVirtualMachineInterface) AddTag(ctx context.Context, value string) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTag", ctx, value)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTag indicates an expected call of AddTag.
func (mr *MockVirtualMachineInterfaceMockRecorder) AddTag(ctx, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTag", reflect.TypeOf((*MockVirtualMachineInterface)(nil).AddTag), ctx, value)
}

// Clone mocks base method.
func (m *MockVirtualMachineInterface) Clone(ctx context.Context, options *proxmox.VirtualMachineCloneOptions) (int, *proxmox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clone", ctx, options)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(*proxmox.Task)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Clone indicates an expected call of Clone.
func (mr *MockVirtualMachineInterfaceMockRecorder) Clone(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clone", reflect.TypeOf((*MockVirtualMachineInterface)(nil).Clone), ctx, options)
}

// Config mocks base method.
func (m *MockVirtualMachineInterface) Config(ctx context.Context, options ...proxmox.VirtualMachineOption) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Config", varargs...)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Config indicates an expected call of Config.
func (mr *MockVirtualMachineInterfaceMockRecorder) Config(ctx any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockVirtualMachineInterface)(nil).Config), varargs...)
}

// Delete mocks base method.
func (m *MockVirtualMachineInterface) Delete(ctx context.Context, options *proxmox.VirtualMachineDeleteOptions) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, options)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockVirtualMachineInterfaceMockRecorder) Delete(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVirtualMachineInterface)(nil).Delete), ctx, options)
}

// DeleteSnapshot mocks base method.
func (m *MockVirtualMachineInterface) DeleteSnapshot(ctx context.Context, name string) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSnapshot", ctx, name)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSnapshot indicates an expected call of DeleteSnapshot.
func (mr *MockVirtualMachineInterfaceMockRecorder) DeleteSnapshot(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSnapshot", reflect.TypeOf((*MockVirtualMachineInterface)(nil).DeleteSnapshot), ctx, name)
}

// Details mocks base method.
func (m *MockVirtualMachineInterface) Details() interfaces.VirtualMachineDetails {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Details")
	ret0, _ := ret[0].(interfaces.VirtualMachineDetails)
	return ret0
}

// Details indicates an expected call of Details.
func (mr *MockVirtualMachineInterfaceMockRecorder) Details() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Details", reflect.TypeOf((*MockVirtualMachineInterface)(nil).Details))
}

// Migrate mocks base method.
func (m *MockVirtualMachineInterface) Migrate(ctx context.Context, options *proxmox.VirtualMachineMigrateOptions) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Migrate", ctx, options)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Migrate indicates an expected call of Migrate.
func (mr *MockVirtualMachineInterfaceMockRecorder) Migrate(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Migrate", reflect.TypeOf((*MockVirtualMachineInterface)(nil).Migrate), ctx, options)
}

// MigratePreconditions mocks base method.
func (m *MockVirtualMachineInterface) MigratePreconditions(ctx context.Context, target string) (*proxmox.VirtualMachineMigratePreconditions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MigratePreconditions", ctx, target)
	ret0, _ := ret[0].(*proxmox.VirtualMachineMigratePreconditions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MigratePreconditions indicates an expected call of MigratePreconditions.
func (mr *MockVirtualMachineInterfaceMockRecorder) MigratePreconditions(ctx, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MigratePreconditions", reflect.TypeOf((*MockVirtualMachineInterface)(nil).MigratePreconditions), ctx, target)
}

// NewSnapshot mocks base method.
func (m *MockVirtualMachineInterface) NewSnapshot(ctx context.Context, name string) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSnapshot", ctx, name)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewSnapshot indicates an expected call of NewSnapshot.
func (mr *MockVirtualMachineInterfaceMockRecorder) NewSnapshot(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSnapshot", reflect.TypeOf((*MockVirtualMachineInterface)(nil).NewSnapshot), ctx, name)
}

// Pause mocks base method.
func (m *MockVirtualMachineInterface) Pause(ctx context.Context) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pause", ctx)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pause indicates an expected call of Pause.
func (mr *MockVirtualMachineInterfaceMockRecorder) Pause(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pause", reflect.TypeOf((*MockVirtualMachineInterface)(nil).Pause), ctx)
}

// Reboot mocks base method.
func (m *MockVirtualMachineInterface) Reboot(ctx context.Context) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reboot", ctx)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reboot indicates an expected call of Reboot.
func (mr *MockVirtualMachineInterfaceMockRecorder) Reboot(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reboot", reflect.TypeOf((*MockVirtualMachineInterface)(nil).Reboot), ctx)
}

// RemoveTag mocks base method.
func (m *MockVirtualMachineInterface) RemoveTag(ctx context.Context, value string) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTag", ctx, value)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveTag indicates an expected call of RemoveTag.
func (mr *MockVirtualMachineInterfaceMockRecorder) RemoveTag(ctx, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTag", reflect.TypeOf((*MockVirtualMachineInterface)(nil).RemoveTag), ctx, value)
}

// ResizeDisk mocks base method.
func (m *MockVirtualMachineInterface) ResizeDisk(ctx context.Context, disk, size string) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResizeDisk", ctx, disk, size)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResizeDisk indicates an expected call of ResizeDisk.
func (mr *MockVirtualMachineInterfaceMockRecorder) ResizeDisk(ctx, disk, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResizeDisk", reflect.TypeOf((*MockVirtualMachineInterface)(nil).ResizeDisk), ctx, disk, size)
}

// Resume mocks base method.
func (m *MockVirtualMachineInterface) Resume(ctx context.Context) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resume", ctx)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resume indicates an expected call of Resume.
func (mr *MockVirtualMachineInterfaceMockRecorder) Resume(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resume", reflect.TypeOf((*MockVirtualMachineInterface)(nil).Resume), ctx)
}

// RollbackSnapshot mocks base method.
func (m *MockVirtualMachineInterface) RollbackSnapshot(ctx context.Context, name string) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackSnapshot", ctx, name)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RollbackSnapshot indicates an expected call of RollbackSnapshot.
func (mr *MockVirtualMachineInterfaceMockRecorder) RollbackSnapshot(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackSnapshot", reflect.TypeOf((*MockVirtualMachineInterface)(nil).RollbackSnapshot), ctx, name)
}

// Shutdown mocks base method.
func (m *MockVirtualMachineInterface) Shutdown(ctx context.Context) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", ctx)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockVirtualMachineInterfaceMockRecorder) Shutdown(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockVirtualMachineInterface)(nil).Shutdown), ctx)
}

// Snapshots mocks base method.
func (m *MockVirtualMachineInterface) Snapshots(ctx context.Context) ([]*proxmox.VirtualMachineSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshots", ctx)
	ret0, _ := ret[0].([]*proxmox.VirtualMachineSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Snapshots indicates an expected call of Snapshots.
func (mr *MockVirtualMachineInterfaceMockRecorder) Snapshots(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshots", reflect.TypeOf((*MockVirtualMachineInterface)(nil).Snapshots), ctx)
}

// Start mocks base method.
func (m *MockVirtualMachineInterface) Start(ctx context.Context) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockVirtualMachineInterfaceMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockVirtualMachineInterface)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockVirtualMachineInterface) Stop(ctx context.Context) (*proxmox.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx)
	ret0, _ := ret[0].(*proxmox.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stop indicates an expected call of Stop.
func (mr *MockVirtualMachineInterfaceMockRecorder) Stop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockVirtualMachineInterface)(nil).Stop), ctx)
}

// MockClusterInterface is a mock of ClusterInterface interface.
type MockClusterInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClusterInterfaceMockRecorder
	isgomock struct{}
}

// MockClusterInterfaceMockRecorder is the mock recorder for MockClusterInterface.
type MockClusterInterfaceMockRecorder struct {
	mock *MockClusterInterface
}

// NewMockClusterInterface creates a new mock instance.
func NewMockClusterInterface(ctrl *gomock.Controller) *MockClusterInterface {
	mock := &MockClusterInterface{ctrl: ctrl}
	mock.recorder = &MockClusterInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterInterface) EXPECT() *MockClusterInterfaceMockRecorder {
	return m.recorder
}

// NextID mocks base method.
func (m *MockClusterInterface) NextID(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextID", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextID indicates an expected call of NextID.
func (mr *MockClusterInterfaceMockRecorder) NextID(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextID", reflect.TypeOf((*MockClusterInterface)(nil).NextID), ctx)
}

// Resources mocks base method.
func (m *MockClusterInterface) Resources(ctx context.Context, filters ...string) (proxmox.ClusterResources, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range filters {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Resources", varargs...)
	ret0, _ := ret[0].(proxmox.ClusterResources)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resources indicates an expected call of Resources.
func (mr *MockClusterInterfaceMockRecorder) Resources(ctx any, filters ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, filters...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resources", reflect.TypeOf((*MockClusterInterface)(nil).Resources), varargs...)
}

// MockStorageInterface is a mock of StorageInterface interface.
type MockStorageInterface struct {
	ctrl     *gomock.Controller
	recorder *MockStorageInterfaceMockRecorder
	isgomock struct{}
}

// MockStorageInterfaceMockRecorder is the mock recorder for MockStorageInterface.
type MockStorageInterfaceMockRecorder struct {
	mock *MockStorageInterface
}

// NewMockStorageInterface creates a new mock instance.
func NewMockStorageInterface(ctrl *gomock.Controller) *MockStorageInterface {
	mock := &MockStorageInterface{ctrl: ctrl}
	mock.recorder = &MockStorageInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageInterface) EXPECT() *MockStorageInterfaceMockRecorder {
	return m.recorder
}

// GetContent mocks base method.
func (m *MockStorageInterface) GetContent(ctx context.Context) ([]*proxmox.StorageContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContent", ctx)
	ret0, _ := ret[0].([]*proxmox.StorageContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContent indicates an expected call of GetContent.
func (mr *MockStorageInterfaceMockRecorder) GetContent(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContent", reflect.TypeOf((*MockStorageInterface)(nil).GetContent), ctx)
}
